# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-09 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('unit', models.CharField(default='500g', max_length=20, verbose_name='单位')),
                ('desc', models.CharField(max_length=1000, verbose_name='描述')),
                ('detail', models.CharField(max_length=2000, verbose_name='商品描述')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/img/goods', verbose_name='商品图片')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品信息表',
                'verbose_name_plural': '商品信息表',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='类名称')),
                ('desc', models.CharField(default='商品描述', max_length=200, verbose_name='类描述')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/img/good_type', verbose_name='商品图片')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品类信息表',
                'verbose_name_plural': '商品类信息表',
                'db_table': 'goods_type',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.GoodsType', verbose_name='类型'),
        ),
    ]
