# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-09 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=40, verbose_name='姓名')),
                ('address', models.CharField(max_length=150, verbose_name='收站点')),
                ('cellphone', models.CharField(max_length=11, verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '收货地址表',
                'verbose_name_plural': '收货地址表',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='用户名称')),
                ('upassword', models.CharField(max_length=200, verbose_name='用户密码')),
                ('uemail', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('uphone', models.CharField(max_length=50, null=True, verbose_name='手机号')),
                ('udatetime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('isban', models.BooleanField(default=False, verbose_name='是否禁用')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo', verbose_name='用户'),
        ),
    ]
