# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-09 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberapp', '0001_initial'),
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(db_column='cart_count', verbose_name='商品数量')),
                ('good', models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
                'db_table': 'cartinfo',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=200, verbose_name='订单编号')),
                ('ads', models.CharField(max_length=200, verbose_name='收件人')),
                ('acot', models.IntegerField(verbose_name='总数')),
                ('acount', models.IntegerField(verbose_name='价格')),
                ('cals', models.TextField(blank=True, null=True, verbose_name='订单详情')),
                ('orderStatus', models.IntegerField(blank=True, choices=[(1, '未支付'), (2, '已支付'), (3, '订单取消')], default=1, verbose_name='是否提交')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'order',
            },
        ),
    ]
